name: Bug Report
description: Describe the bug A clear and concise description of what the bug is
title: "[Bug]: "
labels: [t_Bug]
body:
  - type: markdown
    attributes:
      value: |
        Describe the bug A clear and concise description of what the bug is.
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In what environment did you experience this issue?
      options:
        - Production (https://vision.hmwsinc.com:4200)
        - qa-1 (http://clark.titusgt.com:10942)
        - Prod Clone (http://clark.titusgt.com:10742/)
        - Staging (http://clark.titusgt.com:6542/)
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: In which browser did you experience this issue?
      options:
        - Google Chrome
        - Mozilla Firefox
        - Windows Edge
        - Internet Explorer
        - Safari
        - Opera
        - Brave Browser
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Describe the steps below to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: behavior
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
      placeholder: "The work order must be able to..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? Images?
        You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        For Desktop

        ---

        Please complete the following information
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: In what operating system did you experience this issue?
      options:
        - Windows 11
        - Windows 10
        - Windows 7
        - Windows XP
        - MacOS 10.14 Mojave- 2018.
        - MacOS 10.13 High Sierra- 2017.
        - MacOS 10.12 Sierra- 2016.
        - Ubuntu 21.04
        - Ubuntu 20.04
        - Ubuntu 18.04
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        For Mobile

        ---

        Please complete the following information
  - type: dropdown
    id: phone
    attributes:
      label: Operating system
      description: In what operating system did you experience this issue?
      options:
        - Android 11
        - Android 10
        - Android Pie
        - Android Oreo
        - Android Nougat
        - iOS / iPadOS 15
        - iOS / iPadOS 14
        - iOS / iPadOS 13
        - iOS / iPadOS 12
    validations:
      required: false
